repos:
# Baseline precommit hooks
- repo : https://github.com/pre-commit/pre-commit-hooks
  rev  : v3.2.0
  hooks:
  - id  : trailing-whitespace
  - id  : end-of-file-fixer
  - id  : check-added-large-files
  # - id  : no-commit-to-branch
  #   args: ['--branch', 'main']
  - id  : check-yaml
    args: ['--unsafe']
# Code formatting through Black
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      language_version: python3.11
# Python linting through ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.282
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
