repos:
# Baseline precommit hooks
- repo : https://github.com/pre-commit/pre-commit-hooks
  rev  : v3.2.0
  hooks:
  - id  : trailing-whitespace
  - id  : end-of-file-fixer
  - id  : check-added-large-files
  - id  : no-commit-to-branch
    args: ['--branch', 'main']
  - id  : check-yaml
    args: ['--unsafe']
# Python linting and formatting through ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
