site_name: Forastero
repo_name: intuity/forastero
repo_url: https://github.com/intuity/forastero
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Welcome: index.md
  - Testbench: testbench.md
  - Components:
    - Introduction: components/index.md
    - Interfaces: components/io.md
    - Transactions: components/transaction.md
    - Drivers: components/driver.md
    - Monitors: components/monitor.md
  - Logging: logging.md
  - Parameters: parameters.md
  - Sequences: sequences.md
  - Scoreboards: scoreboard.md
  - Testcases: testcases.md
