name: Forastero Documentation

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages   : write
  id-token: write

# Allow only one concurrent deployment to GitHub pages, but don't cancel running
# builds and wait for completion
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_docs:
    name           : Build Documentation
    runs-on        : ubuntu-latest
    timeout-minutes: 15
    steps          :
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name : Install Poetry and environment
        shell: bash
        run  : |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with dev
      - name: Build documentation
        run: |
          poetry run mkdocs build
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

  deploy_docs:
    name           : Deploy Documentation
    runs-on        : ubuntu-latest
    timeout-minutes: 15
    needs          :
      - build_docs
    steps          :
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
