name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name           : Check that pre-commit passes
    runs-on        : ubuntu-latest
    timeout-minutes: 15
    steps          :
    - uses: actions/checkout@v4
    - uses: ./.github/composites/setup
      with:
        python-version: 3.11
    - name: Run Ruff formatting check
      run: poetry run ruff format --check .
    - name: Run Ruff linting check
      run: poetry run ruff check .
    - name: Run precommit checks
      env:
        SKIP: no-commit-to-branch
      run: poetry run pre-commit run --all-files
