name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name           : Check that pre-commit passes
    runs-on        : ubuntu-latest
    timeout-minutes: 15
    steps          :
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name : Install Poetry and environment
        shell: bash
        run  : |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with dev
      - name: Run Ruff formatting check
        run: poetry run ruff format --check .
      - name: Run Ruff linting check
        run: poetry run ruff check .
      - name: Run precommit checks
        env:
          SKIP: no-commit-to-branch
        run: poetry run pre-commit run --all-files
