name: Forastero Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run_example:
    name           : Run Example Project
    runs-on        : ubuntu-latest
    timeout-minutes: 15
    steps          :
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name : Setup Verilator 5.040
        shell: bash
        run  : |
          sudo apt update -y
          sudo apt-get install -y git help2man perl python3 make autoconf \
                                  g++ flex bison ccache libgoogle-perftools-dev \
                                  numactl perl-doc libfl2 libfl-dev zlib1g \
                                  zlib1g-dev
          git clone https://github.com/verilator/verilator
          cd verilator
          git checkout v5.040
          autoconf
          ./configure
          make -j $(nproc)
          sudo make install
      - name : Install Poetry and environment
        shell: bash
        run  : |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with dev
      - name : Run Arbiter Strict Example
        shell: bash
        run  : |
          cd examples/arbiter_strict
          poetry run make
      - name : Run Arbiter Window Example
        shell: bash
        run  : |
          cd examples/arbiter_window
          poetry run make
